-- 001: the whole schema as it stood when the store moved to Postgres.
-- Forward-only. Never edit an applied migration; add a new numbered one.
--
-- This is the SQLite history 001..006 (data spine + gate ledger, the serving
-- path, the tip list and its three widenings) collapsed into one file, because
-- 004 and 005 were SQLite-only table rebuilds -- SQLite cannot alter a CHECK
-- constraint; Postgres can -- and a history that starts with a rebuild of a
-- table it has not created is not a history. Every table, column, index and
-- constraint below is the one the SQLite store ended with, in the same order,
-- so the copier (docs/POSTGRES_PLAN.md Phase B) can move rows column for
-- column. The design notes are carried from the original files; the decisions
-- they record still hold.
--
-- Types, on decision D3 of the plan: dates and timestamps stay TEXT
-- ('YYYY-MM-DD' and 'YYYY-MM-DD HH:MM:SS', always UTC) so the API's output is
-- byte-identical across the move; REAL became double precision; INTEGER
-- PRIMARY KEY became an identity column that still accepts an explicit id.

-- Canonical club registry. One row per real club; football-data short names and
-- FBref squad names both bridge into this table via team_aliases.
CREATE TABLE teams (
    team_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name TEXT NOT NULL UNIQUE
);

-- The hand-maintained bridge. `source` is 'football-data' or 'fbref'.
-- An alias is unique per source; the same club may hold several per source
-- (e.g. fbref writes both 'Torquay United' and 'Torquay').
CREATE TABLE team_aliases (
    source   TEXT NOT NULL,
    alias    TEXT NOT NULL,
    team_id  INTEGER NOT NULL REFERENCES teams(team_id),
    PRIMARY KEY (source, alias)
);

-- Normalised match corpus. Odds columns are era-unified: Betbrain aggregates
-- (2010-11..2018-19) and market Avg/Max (2019-20..) land in the same fields,
-- distinguished by odds_era. Stat columns are NULL where the source omits them
-- (EC has no shots/corners/fouls from 2016-17).
CREATE TABLE matches (
    match_id       TEXT PRIMARY KEY,
    season         TEXT NOT NULL,
    division       TEXT NOT NULL,
    match_date     TEXT NOT NULL,          -- ISO yyyy-mm-dd
    kickoff_time   TEXT,                   -- HH:MM, present from 2019-20 only
    home_team_id   INTEGER NOT NULL REFERENCES teams(team_id),
    away_team_id   INTEGER NOT NULL REFERENCES teams(team_id),

    fthg INTEGER, ftag INTEGER, ftr TEXT,
    hthg INTEGER, htag INTEGER, htr TEXT,
    referee TEXT,

    home_shots INTEGER, away_shots INTEGER,
    home_sot   INTEGER, away_sot   INTEGER,
    home_corners INTEGER, away_corners INTEGER,
    home_fouls INTEGER, away_fouls INTEGER,
    home_yellow INTEGER, away_yellow INTEGER,
    home_red INTEGER, away_red INTEGER,

    -- pre-closing (collected Friday/Tuesday PM: BEFORE team news)
    b365_h DOUBLE PRECISION, b365_d DOUBLE PRECISION, b365_a DOUBLE PRECISION,
    ps_h DOUBLE PRECISION, ps_d DOUBLE PRECISION, ps_a DOUBLE PRECISION,
    avg_h DOUBLE PRECISION, avg_d DOUBLE PRECISION, avg_a DOUBLE PRECISION,
    max_h DOUBLE PRECISION, max_d DOUBLE PRECISION, max_a DOUBLE PRECISION,
    avg_over25 DOUBLE PRECISION, avg_under25 DOUBLE PRECISION,
    max_over25 DOUBLE PRECISION, max_under25 DOUBLE PRECISION,
    ah_line DOUBLE PRECISION, avg_ah_h DOUBLE PRECISION, avg_ah_a DOUBLE PRECISION,

    -- closing (at kickoff: AFTER team news). Pinnacle from 2012-13, the rest
    -- from 2019-20. Pinnacle collapses mid-2025-26, hence the Avg fallback.
    close_ps_h DOUBLE PRECISION, close_ps_d DOUBLE PRECISION, close_ps_a DOUBLE PRECISION,
    close_b365_h DOUBLE PRECISION, close_b365_d DOUBLE PRECISION, close_b365_a DOUBLE PRECISION,
    close_avg_h DOUBLE PRECISION, close_avg_d DOUBLE PRECISION, close_avg_a DOUBLE PRECISION,
    close_max_h DOUBLE PRECISION, close_max_d DOUBLE PRECISION, close_max_a DOUBLE PRECISION,
    close_avg_over25 DOUBLE PRECISION, close_avg_under25 DOUBLE PRECISION,
    close_ah_line DOUBLE PRECISION, close_avg_ah_h DOUBLE PRECISION, close_avg_ah_a DOUBLE PRECISION,

    odds_era    TEXT NOT NULL,             -- 'betbrain' | 'market'
    source_file TEXT NOT NULL
);

CREATE INDEX idx_matches_season_div ON matches (season, division);
CREATE INDEX idx_matches_date ON matches (match_date);
CREATE INDEX idx_matches_home ON matches (home_team_id);
CREATE INDEX idx_matches_away ON matches (away_team_id);

-- One row per player per club-spell per season (FBref Standard Stats).
-- Mid-season transfers produce two rows sharing player_id; never group by name.
-- player_id_kind='slug' marks the National League pre-2018-19 pseudo-IDs, which
-- are NOT stable identities and must not be joined across seasons or divisions.
CREATE TABLE player_seasons (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season         TEXT NOT NULL,
    division       TEXT NOT NULL,
    player_id      TEXT NOT NULL,
    player_id_kind TEXT NOT NULL,          -- 'hex' | 'slug'
    player_name    TEXT NOT NULL,
    nation         TEXT,
    position       TEXT,
    age            INTEGER,
    born           INTEGER,
    team_id        INTEGER REFERENCES teams(team_id),
    squad_raw      TEXT NOT NULL,

    mp INTEGER, starts INTEGER, minutes INTEGER, nineties DOUBLE PRECISION,
    goals INTEGER, assists INTEGER, goals_non_pk INTEGER,
    pk INTEGER, pk_att INTEGER, cards_y INTEGER, cards_r INTEGER,

    source_file TEXT NOT NULL
);

CREATE INDEX idx_player_seasons_season_div ON player_seasons (season, division);
CREATE INDEX idx_player_seasons_player ON player_seasons (player_id);
CREATE INDEX idx_player_seasons_team ON player_seasons (team_id, season);

-- Append-only. Records every gate, sweep and exploratory query run against the
-- development set, and every unseal of the holdout. This is what gives the
-- deflated-performance / PBO calculation a real trial count to work from, so it
-- is load-bearing rather than bookkeeping (SPEC §5.3). Never UPDATE or DELETE.
-- Row ids are quoted in the documents; they are loaded with their original
-- values by scripts/export_ledger.py --restore, never by the copier.
CREATE TABLE gate_ledger (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TEXT NOT NULL
                 DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    kind         TEXT NOT NULL,            -- 'holdout_unseal' | 'gate' | 'sweep' | 'probe'
    name         TEXT NOT NULL,
    purpose      TEXT,                     -- Purpose of the corpus read
    seasons      TEXT,                     -- comma-separated season codes touched
    divisions    TEXT,
    detail       TEXT,                     -- free-form JSON
    reason       TEXT
);

CREATE INDEX idx_gate_ledger_kind ON gate_ledger (kind);

-- Upcoming matches pulled from football-data.co.uk's rolling fixtures feed.
-- Separate from `matches` on purpose: a fixture has no result, and letting the
-- two share a table would mean every query over the corpus had to remember to
-- exclude unplayed rows. When the result arrives the grader writes it into
-- `matches` and links back by fixture_id.
--
-- The feed is a ~7-day rolling window and republishes the same fixture with
-- updated prices, so upserts on (division, match_date, home, away) are the
-- normal case rather than an error.
CREATE TABLE fixtures (
    fixture_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division       TEXT NOT NULL,
    match_date     TEXT NOT NULL,          -- ISO yyyy-mm-dd
    kickoff_time   TEXT,                   -- HH:MM as published
    home_team_id   INTEGER NOT NULL REFERENCES teams(team_id),
    away_team_id   INTEGER NOT NULL REFERENCES teams(team_id),
    -- Pre-close prices as published with the fixture. Same unified schema as
    -- `matches`, so engine.odds reads both without branching.
    avg_h          DOUBLE PRECISION,
    avg_d          DOUBLE PRECISION,
    avg_a          DOUBLE PRECISION,
    max_h          DOUBLE PRECISION,
    max_d          DOUBLE PRECISION,
    max_a          DOUBLE PRECISION,
    avg_over25     DOUBLE PRECISION,
    avg_under25    DOUBLE PRECISION,
    ah_line        DOUBLE PRECISION,
    avg_ah_h       DOUBLE PRECISION,
    avg_ah_a       DOUBLE PRECISION,
    first_seen_at  TEXT NOT NULL
                   DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at     TEXT NOT NULL
                   DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    source_file    TEXT NOT NULL,
    UNIQUE (division, match_date, home_team_id, away_team_id)
);

CREATE INDEX idx_fixtures_date ON fixtures (match_date);

-- Append-only. One row per (fixture, artifact, information set) served.
-- Lambdas are stored RAW so that any later pmf change -- a different line, a
-- correction, a calibration -- can be recomputed from what the model actually
-- said, rather than from probabilities that have already been rounded through
-- one particular derivation.
CREATE TABLE predictions (
    prediction_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id      INTEGER NOT NULL REFERENCES fixtures(fixture_id),
    served_at       TEXT NOT NULL
                    DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    model_version   TEXT NOT NULL,          -- artifact version string
    information_set TEXT NOT NULL,          -- 'pre_close' | 'closing'
    lam_h           DOUBLE PRECISION NOT NULL,
    lam_a           DOUBLE PRECISION NOT NULL,
    p_home          DOUBLE PRECISION NOT NULL,
    p_draw          DOUBLE PRECISION NOT NULL,
    p_away          DOUBLE PRECISION NOT NULL,
    p_over25        DOUBLE PRECISION NOT NULL,
    p_under25       DOUBLE PRECISION NOT NULL,
    calibrated      INTEGER NOT NULL DEFAULT 0,   -- 0 until P3 lands
    UNIQUE (fixture_id, model_version, information_set, served_at)
);

CREATE INDEX idx_predictions_fixture ON predictions (fixture_id);

-- Append-only paper book. Grading columns are written BESIDE the bet, never
-- over it: the price and probability that justified the bet must survive
-- whatever happened next, or the record cannot be audited.
--
-- `breakeven_prob` is the RAW 1/odds -- vig-inclusive -- because that is the
-- bar a bet actually has to clear. It is deliberately not the de-vigged
-- probability, which is the market's opinion and belongs in CLV, not here.
-- Conflating the two is the single easiest way to manufacture a fictional edge.
CREATE TABLE paper_bets (
    bet_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id   INTEGER NOT NULL REFERENCES predictions(prediction_id),
    fixture_id      INTEGER NOT NULL REFERENCES fixtures(fixture_id),
    placed_at       TEXT NOT NULL
                    DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    market          TEXT NOT NULL,          -- '1x2' | 'ou25'
    side            TEXT NOT NULL,          -- 'H'|'D'|'A'|'over'|'under'
    price           DOUBLE PRECISION NOT NULL,          -- decimal odds taken
    price_source    TEXT NOT NULL,          -- which column the price came from
    model_prob      DOUBLE PRECISION NOT NULL,
    breakeven_prob  DOUBLE PRECISION NOT NULL,          -- 1/price, VIG-INCLUSIVE
    edge            DOUBLE PRECISION NOT NULL,          -- model_prob - breakeven_prob
    expected_value  DOUBLE PRECISION NOT NULL,          -- model_prob * price - 1
    stake           DOUBLE PRECISION NOT NULL,
    rule_version    TEXT NOT NULL,
    -- written by the grader, after the fact
    settled_at      TEXT,
    outcome         TEXT,                   -- 'win' | 'lose' | 'void'
    pnl             DOUBLE PRECISION
);

CREATE INDEX idx_paper_bets_fixture ON paper_bets (fixture_id);
CREATE INDEX idx_paper_bets_settled ON paper_bets (settled_at);

-- Append-only. CLV is the primary metric (SPEC §5.1): did the price we took
-- beat the closing line? Measured against the DE-VIGGED close, because the
-- question is whether we were ahead of the market's final opinion, not whether
-- we beat a number inflated by margin.
CREATE TABLE clv_grades (
    grade_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_id          INTEGER NOT NULL REFERENCES paper_bets(bet_id),
    graded_at       TEXT NOT NULL
                    DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    bet_price       DOUBLE PRECISION NOT NULL,
    close_price     DOUBLE PRECISION NOT NULL,
    close_source    TEXT NOT NULL,          -- 'PSC' | 'AvgC' -- never mixed silently
    bet_prob        DOUBLE PRECISION NOT NULL,          -- de-vigged, at bet time
    close_prob      DOUBLE PRECISION NOT NULL,          -- de-vigged, at close
    clv             DOUBLE PRECISION NOT NULL,          -- close_prob - bet_prob; >0 = we were early
    clv_pct         DOUBLE PRECISION NOT NULL,          -- bet_price / close_price - 1
    UNIQUE (bet_id)
);

-- Append-only snapshot of what was live for a serving cycle. Without this,
-- "which model priced this bet, under which recalibration" is answerable only
-- by guessing from timestamps.
CREATE TABLE serving_state (
    state_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TEXT NOT NULL
                    DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    cycle_label     TEXT NOT NULL,          -- e.g. '2026-08-15'
    model_version   TEXT NOT NULL,
    artifact_path   TEXT,
    fixtures_seen   INTEGER NOT NULL,
    predictions_written INTEGER NOT NULL,
    bets_written    INTEGER NOT NULL,
    rule_version    TEXT NOT NULL,
    notes           TEXT
);

-- Registry of frozen artifacts. The version string is derived from the
-- artifact's own contents (engine.serve.artifact), so a row here is a claim
-- that can be checked, not a label that has to be trusted.
CREATE TABLE model_runs (
    model_version   TEXT PRIMARY KEY,
    created_at      TEXT NOT NULL
                    DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    fitted_at       TEXT NOT NULL,          -- training cutoff, not wall clock
    config_label    TEXT NOT NULL,
    n_train         INTEGER NOT NULL,
    n_teams         INTEGER NOT NULL,
    corpus_digest   TEXT NOT NULL,
    artifact_path   TEXT
);

-- The tip list -- what the confidence rule published, and how it did.
--
-- A tip is not a bet, and this table is not `paper_bets`. `paper_bets` records
-- a *value* decision: the model's probability beat the price's break-even.
-- A tip records a *confidence* decision, which ignores price entirely
-- (`engine/serve/tips.py`). The two rules select nearly disjoint fixtures --
-- value lives on longshots, confidence on favourites -- so they are separate
-- tables rather than one table with a rule column, and no query can average
-- across them by accident.
--
-- `UNIQUE (fixture_id, rule_version)` is the safety property, enforced here
-- rather than in Python: **one published tip per fixture per rule.** A tipster
-- that publishes two contradictory recommendations for the same match has no
-- defensible strike rate, and re-running a cycle at a lower threshold must not
-- be able to produce one. Changing the threshold means bumping rule_version.
--
-- `side` carries every code a rule has emitted: the outright 'H'/'D'/'A'
-- (confidence-v1), the double chances '1X'/'X2'/'12' (v2, PRODUCT.md 3a) and
-- the concrete +1.5 handicaps 'H+1.5'/'A+1.5' (confidence-v3, BACKLOG.md B21:
-- concrete rather than fav-relative so a tip settles from side + final score
-- alone; half line, so no push and no void). `floor` and `ceiling` are the
-- rule's two settings stored per tip; `ceiling` is NULL for tips published
-- before the rule had one.
--
-- Grading columns are written by the grader BESIDE the tip, never over it.
-- Both price levels are settled, not one: strike rate is what the product is
-- sold on and return is what the customer gets, and the gap between them is
-- the whole reason this table records more than a win flag. `fthg`/`ftag`
-- are the score the outcome was settled from (margin-aware under v3), so the
-- record keeps the exact figures and the site can show a scoreline without
-- inventing one; NULL for tips settled before the column existed. `fixtures`
-- still carries no result.
CREATE TABLE tips (
    tip_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id   INTEGER NOT NULL REFERENCES predictions(prediction_id),
    fixture_id      INTEGER NOT NULL REFERENCES fixtures(fixture_id),
    published_at    TEXT NOT NULL
                    DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    side            TEXT NOT NULL CHECK (side IN ('H', 'D', 'A', '1X', 'X2', '12',
                                                  'H+1.5', 'A+1.5')),
    model_prob      DOUBLE PRECISION NOT NULL,
    floor           DOUBLE PRECISION NOT NULL,
    ceiling         DOUBLE PRECISION,
    -- Carried for reporting only. Neither column takes any part in selection;
    -- if either ever does, the product has become a value rule.
    best_price      DOUBLE PRECISION,
    avg_price       DOUBLE PRECISION,
    rule_version    TEXT NOT NULL,
    settled_at      TEXT,
    outcome         TEXT CHECK (outcome IN ('win', 'lose', 'void')),
    pnl_best        DOUBLE PRECISION,
    pnl_avg         DOUBLE PRECISION,
    fthg            INTEGER,
    ftag            INTEGER,
    UNIQUE (fixture_id, rule_version)
);

CREATE INDEX idx_tips_unsettled ON tips (settled_at) WHERE settled_at IS NULL;
CREATE INDEX idx_tips_fixture ON tips (fixture_id);
