-- 002: accounts and sessions for Google sign-in (docs/AUTH_PLAN.md, B25).
-- Forward-only. Never edit an applied migration; add a new numbered one.
--
-- First tables written by the API rather than the cycle, and first to use
-- TIMESTAMPTZ/BOOLEAN: POSTGRES_PLAN.md D3 kept the baseline's UTC-text
-- columns so the API's output stayed byte-identical across the move; that
-- argument does not reach tables that did not exist then, and 1.2 names
-- real types for exactly these. Sessions do time arithmetic (expiry,
-- sliding refresh), which is why it matters here.
--
-- One row per Google account. `google_sub` is the identity (Google's stable
-- subject id), not the email, which Google allows to change. Token fields
-- are refreshed on every sign-in (ON CONFLICT DO UPDATE in api/main.py).
-- The phone is captured ONCE after the first sign-in (AUTH_PLAN.md D5):
-- E.164, normalised server-side with `phonenumbers`; the CHECK is the last
-- line of defence, not the validator. `phone_country` is the ISO 3166-1
-- alpha-2 region it was parsed under, for a later SMS step.
-- `phone_verified_at` stays NULL until SMS verification exists. UNIQUE on
-- the phone is the property the number is collected for -- one number, one
-- account -- and the API answers 409 rather than letting two share it.
CREATE TABLE users (
    user_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub        TEXT NOT NULL UNIQUE,
    email             TEXT NOT NULL,
    email_verified    BOOLEAN NOT NULL DEFAULT FALSE,
    name              TEXT,
    picture_url       TEXT,
    phone_e164        TEXT UNIQUE CHECK (phone_e164 ~ '^\+[1-9][0-9]{6,14}$'),
    phone_country     TEXT CHECK (phone_country ~ '^[A-Z]{2}$'),
    phone_captured_at TIMESTAMPTZ,
    phone_verified_at TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((phone_e164 IS NULL) = (phone_captured_at IS NULL)),
    CHECK (phone_e164 IS NULL OR phone_country IS NOT NULL)
);

-- One row per browser sign-in. The cookie holds a random 256-bit token; this
-- table holds its SHA-256, so a copy of the database or a backup (which now
-- carries PII -- scripts/backup.sh) cannot be replayed as a login. A session
-- ends when `expires_at` passes (sliding, refreshed at most daily by
-- api.main.current_user), when `revoked_at` is set (sign out), or when its
-- user is deleted (CASCADE). Revoked rows are kept, not deleted. The client
-- IP is NOT stored -- PII with no consumer; `user_agent` is, truncated.
CREATE TABLE user_sessions (
    session_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash    TEXT NOT NULL UNIQUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ NOT NULL,
    revoked_at    TIMESTAMPTZ,
    user_agent    TEXT
);

CREATE INDEX idx_user_sessions_user ON user_sessions (user_id);
CREATE INDEX idx_user_sessions_live ON user_sessions (expires_at) WHERE revoked_at IS NULL;
